default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 10.131.137.161
  port: 5432
  timeout: 5000
  username: <%= ENV["PROYECTOGPS_DATABASE_USERNAME"] %>
  password: <%= ENV["PROYECTOGPS_DATABASE_PASSWORD"] %>
 
development:
  <<: *default
  database: proyectoGPS_development

test:
  <<: *default
  database: proyectoGPS_test

production:
  <<: *default
  database: proyectoGPS_production
